### ISSUE TITLE
Error message, maybe related to special character in URL

### ISSUE THREAD

**Issue by jkanner** [dvolgyes/zenodo_get#11]
Hi!  Thank you for making this great package.

I'm finding I get an error message when using on this record:

https://zenodo.org/record/5645777#.YZbhzS1h2-g

`zenodo_get 5645776`

I think it fails on the file with a "+" sign in the name

**Comment by farr** [comment]
Can confirm: definitely due to the '%2B' in the URL (which corresponds to the '+' characters in the filename).

**Comment by dvolgyes** [comment]
Hopefully I fixed it without breaking other things. I pushed a new version to pypi.
Let me know if it still has issues. (It is a rather large record, I did not wait to fully download it.)

**Comment by dvolgyes** [comment]
And thanks for reporting the issue. :)

**Comment by jkanner** [comment]
@farr @dvolgyes   Thank you!   I really appreciate the quick help.   -jonah
