### ISSUE TITLE
restricted repositories can't be used as download target

### ISSUE THREAD

**Issue by jkabisch** [dvolgyes/zenodo_get#18]
Thank you very much for your excellent tool!
I need to download files from repositories with restricted access. I cannot find a way to provide a private token to zenodo_get.

Expected behavior:

- when accessing a restricted repository, a URL with a token is provided from zenodo. See following example with a heavily reduced, random token, token is in my case 226 alphanumerical characters including underscores

https://zenodo.org/record/8039248?token=eyJhbGciOiJIUzUxMiIsImV4cCI6MTY4OTQ1

Observed behavior:

- this link cannot be used as the record identifier: 

`./zenodo_get -r 8039248?token=eyJhbGciOiJIUzUxMiIsImV4cCI6MTY4OTQ1
Traceback (most recent call last):
  File "/home/jfk/.local/bin/./zenodo_get", line 8, in <module>
    sys.exit(zenodo_get())
  File "/home/jfk/.local/lib/python3.10/site-packages/zenodo_get/zget.py", line 297, in zenodo_get
    files = js['files']
KeyError: 'files'
`

**Comment by dvolgyes** [comment]
Hi,

Indeed, private repositories were not implemented.
I will try to take a look into it in the next days.

**Comment by jkabisch** [comment]
Thank you. Here is a link to a restricted repo with some random files. simply request access if this helps you:

https://zenodo.org/record/8045975

**Comment by ricardobarroslourenco** [comment]
It would be a great enhancement.

**Comment by dvolgyes** [comment]
I didn't have time before, but now it should work. 
You need to create a personal access token, and use that to access the files, something like:
zenodo_get -r 8039248 -a  TOKEN
(I tried the above token, but didn't work for me, but when I created my own token for my own private data, then it works.)

The record?token= format is a bit messy, I didn't have much time to fix it, so maybe in the future, but for now '-a' should work. 
I pushed the new version to pypi, so you don't have to clone the repository.
Let me know if it works or not.

**Comment by dvolgyes** [comment]
Probably works. :)
