### ISSUE TITLE
zenodo_get.py: command not found

### ISSUE THREAD

**Issue by mpariente** [dvolgyes/zenodo_get#2]
After installing zenodo_get from pip, I get this error 

`zenodo_get.py: command not found`

Could you help please

**Comment by dvolgyes** [comment]
I guess your pip directory is not on your search path.
You could try this:
python3 -m zenodo_get
If this works, then it is correctly installed, but you need to set your PATH variable.
E.g. on Ubuntu, this is the /home/USERNAME/.local/bin

Could you describe: operating system, exact commands you used for installation, python version, python environment (e.g. ubuntu's, conda, ubuntu+virtualenv, etc.)

**Comment by mpariente** [comment]
Worked like a charm with `python3 -m zenodo_get`, thanks !

- Ubuntu 18.04
- Installed with `pip install zenodo_get`
- Python 3.6 from virtualenv (pip was the one from the virtualenv)
- Both /home/mparient/.virtualenvs/venv_name/bin and  /home/mparient/.local/bin are in my PATH.

**Comment by dvolgyes** [comment]
Could you check the installed files?
E.g. find /home/mparient/.virtualenvs/ | grep zenodo_get
and find /home/mparient/.local/ | grep zenodo_get

There should be two groups installed. One is the module, some files in a library directory,
and one executable somewhere in a bin directory. This second is not found somehow.
There are two options: it is not installed, or it is there, but not found.

While the binary is very short, basically just calling the module, it would be nice to fix it.
(You could manually download the file and just put a directory which is on the PATH, 
but i would like the understand why pip did not do it.)

**Comment by mpariente** [comment]
Actually, I should have realized earlier but the command is `zenodo_get` not `zenodo_get.py`. 
`zenodo_get` works out of the box. 
You should probably update the README.

**Comment by dvolgyes** [comment]
Thanks for the feedback. Actually, it used to be zenodo_get.py, but i changed to 'entry_points' in the packaging, and the file is automatically generated by the setup.py, so i forgot to update the documentation. I will do it, thanks.

**Comment by mpariente** [comment]
I just learned about console_scripts in setup.py, I didn't know about them and it's pretty cool, thanks ! :wink:
