### ISSUE TITLE
DOI Needs an Authentication

### ISSUE THREAD

**Issue by Chrisa142857** [dvolgyes/zenodo_get#9]
Hello there~

It seems that the dataset needs an authentication:
```
Traceback (most recent call last):
  File "/usr/local/bin/zenodo_get", line 8, in <module>
    sys.exit(zenodo_get())
  File "/usr/local/lib/python3.7/dist-packages/zenodo_get/zget.py", line 296, in zenodo_get
    files = js['files']
KeyError: 'files'
```
Is there any solution?

Best regard!

**Comment by dvolgyes** [comment]
Hi,

Thanks for reporting.
Could you submit the command line you used, including the DOI?
Maybe it is the item itself, maybe some other bug, maybe API change,
but it is easier to debug it if you provide this context. Thanks.

**Comment by Chrisa142857** [comment]
Here is it.
```
!zenodo_get "10.5281/zenodo.4652376" -k -w urls.txt
```

**Comment by dvolgyes** [comment]
This record has restricted access, zenogo_get cannot handle such request.
Simply, I did not have access to restricted records and I couldn't test it. 
I might add support later, but not on short term.
The only way currently is logging in, and (if you got permission from the owner),
then download the data files one by one from the website.

**Comment by dvolgyes** [comment]
By the way, even if I could generate download link (`-w`), the downloaders will also not have
implemented authentication for zenodo, so the links would be useless anyway.

**Comment by Chrisa142857** [comment]
Fine. I just want to directly download the data to my colab, and I'm also looking at the Zenodo API to find a way. Whatever, your reply is helpful, thanks~
